DEEPSORT:
#   REID_CKPT: "deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7"
  REID_CKPT: "/home/dyros/JH/dl/parking_spot_corner_detector/deep_sort_pytorch/deep_sort/deep/resnet18_margin_0.3_more_data_epoch_300.pth" 
#   REID_CKPT: "/home/yhpark/SimCLR/runs/Aug26_08-11-35_yhpark-3080ti/checkpoint_0200.pth.tar"
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.2
  NMS_MAX_OVERLAP: 0.5
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 70
  N_INIT: 3
  NN_BUDGET: 100
  PAD: 20
